export const passPrice = { 
    school:{
        twoPoint:{
            monthly:"0",
            quaterly:"0",
            annual:"0"
        },
        threePoint:{
            monthly:"0",
            quaterly:"0",
            annual:"0"
        }
    },
    college:{
        twoPoint:{
            monthly:"150",
            quaterly:"300",
            annual:"800"
        },
        threePoint:{
            monthly:"270",
            quaterly:"450",
            annual:"1200"
        }
    },
    general:{
        twoPoint:{
            monthly:"200",
            quaterly:"600",
            annual:"1500"
        },
        threePoint:{
            monthly:"300",
            quaterly:"900",
            annual:"1800",
        }
    },
};